#!/bin/sh

# Configura a pasta raiz enquanto o pacote no e instalado
RAIZ=`pwd`

# Diretorio de trabalho
DIRTRABALHO=$RAIZ/var/lib/dependencias

# Lista dos repositorios usados
REPOSITORIOS=$RAIZ/etc/dependencias/repositorio

ARQUIVOS="FILE_LIST FILELIST.TXT MANIFEST.bz2"

# Atualiza as informacoes sobre os pacotes dos repositorios
function atualizar()
{
  for repositorio in `cat $REPOSITORIOS`; do
    Nome_repositorio=`echo $repositorio | cut -f1 -d '%'`
    endereco_repositorio=`echo $repositorio | cut -f2 -d '%'`

    if [ ! -e $DIRTRABALHO/$Nome_repositorio ]; then
      mkdir -p $DIRTRABALHO/$Nome_repositorio
    fi

    cd $DIRTRABALHO/$Nome_repositorio
    for arquivo in $ARQUIVOS; do
      wget -c $endereco_repositorio/$arquivo
      if [ "$arquivo" == "FILE_LIST" ]; then
	mv FILE_LIST FILELIST.TXT
      fi
    done
  done
}

# Formata o arquivo MANIFEST
function formatar_MANIFEST()
{
  for MANIFEST in `find $DIRTRABALHO | grep 'MANIFEST.bz2'`; do
    repositorio=`echo $MANIFEST | rev | cut -d/ -f2 | rev`

    echo "Formatando o arquivo MANIFEST.bz2 do repositorio: $repositorio"
    bunzip2 -c $MANIFEST | sed -n '/[^\/\|\=]$\|^$/p' | sed 's/.*\///' | tr '\n' ' ' | sed 's/   /\n/g' > ${DIRTRABALHO}/${repositorio}/filelist
  done
}

function pesquisar()
{
  for filelist in `find $DIRTRABALHO | grep 'filelist'`; do
    resultado=`grep "$1" $filelist | awk '{print $1}'`
    echo $resultado
  done
}

# function baixar()
# {
#     endereco=`cat $REPOSITORIOS | cut -f2 -d '%'`
#     repositorios=`cat $REPOSITORIOS | cut -f1 -d '%'`
#     for repositorio in $repositorios; do
#       caminho=`grep "$1" $DIRTRABALHO/$repositorio/FILELIST.TXT`
#       echo $caminho
#     done
# }

#function dependencia()
#{
#  dependencias=`ldd $(which $1) | grep 'not found' | cut -d. -f1`
#
#  for dependencia in $dependencias;
#  do
#    echo $i
#  done
#}


function uso()
{
  echo -e "\n\t Gerenciador de Dependencias \n\
    Uso:\n\
    \t $0 [atualizar]\n
    \t $0 [pesquisar] {PADRAO|PACOTE}\n"
}

# Mostra ajuda se nao entrar com argumentos
if [ $# -eq 0 ]; then
  uso
else
  case $1 in
    atualizar)
      atualizar
      formatar_MANIFEST
    ;;
    dependencia)
	dependencia $2
    ;;
    pesquisar)
      if [ -n "$2" ]; then 
	pacotes=`pesquisar $2`
	for pacote in $pacotes; do
	  echo $pacote
	done
      else
	uso
      fi
    ;;
    baixar)
      if [ -n "$2" ]; then 
	baixar $2
      else
	uso
      fi
    ;;
    *)
      echo -e "Opcao desconhecida.\n"
      uso
    ;;
  esac
fi
