#!/bin/sh

# Variaves
# Configura a pasta raiz enquanto o pacote não é instalado
RAIZ=/home/paulo/projetos/Dependencias # teste - remover quando terminar de testar

# Diretorio de configuração
CONF=$RAIZ/etc/dependencias

# Diretorio da biblioteca
BIBLIOTECA=$RAIZ/usr/libexec/dependencias

# Carrega as configurações
. $CONF/config.sh

# Carrega a biblioteca
. $BIBLIOTECA/biblioteca.sh

function uso()
{
  echo -e "\t Gerenciador de Dependencias \n\
    Uso:\n\
    \t $0 {atualizar|pesquisar} {PADRAO|PACOTE}"
}

# Mostra ajuda se não entrar com argumentos
if [ $# -eq 0 ]; then
  uso
else
  case $1 in
    atualizar)
      atualizar
      formatar_MANIFEST
    ;;
    dependencia)
	dependencia $2
    ;;
    pesquisar)
      if [ -n "$2" ]; then 
	for pacote in $(pesquisar $2); do
	  echo $pacote
	done
      else
	uso
      fi
    ;;
    *)
      echo -e "Opcao desconhecida.\n"
      uso
    ;;
  esac
fi