#!/bin/sh

# Variaves
# Configura a pasta raiz enquanto o pacote não é instalado
RAIZ=/home/paulo/projetos/GerenciadorPacote/pacotes # teste - remover quando terminar de testar

# Diretorio de configuração
CONF=$RAIZ/etc/pacotes

# Diretorio da biblioteca
BIBLIOTECA=$RAIZ/usr/libexec/pacotes

# Carrega as configurações
. $CONF/config.sh

# Carrega a biblioteca
. $BIBLIOTECA/biblioteca.sh

function uso()
{
  echo -e "\t Gerenciador de Pacotes \n\
    Uso:\n\
    \t pacotes {atualizar|pesquisa_pacote|pesquisa_arquivo} {PADRAO|PACOTE}
    "
}

# Mostra ajuda se não entrar com argumentos
if [ $# -eq 0 ]; then
  uso
else
  case $1 in
    atualizar)
      if [ -n "$2" ]; then
	echo "Iqnorando argumentos extras." >&2 >&1
      fi
    atualizar
    formatar_MANIFEST
    ;;
    pesquisa_pacote)
      if [ -n "$2" ]; then 
	pesquisa_pacote $2
      else
	uso
      fi
    ;;
    pesquisa_arquivo)
      if [ -n "$2" ]; then 
	pesquisa_arquivo $2
      else
	uso
      fi
    ;;
    *)
      echo -e "Opcao desconhecida.\n"
      uso
    ;;
  esac
fi